type User {
  id: ID!
  email: String!
  name: String
  created: String
}

# input UserInput {
#   name: String!
#   email: String!
#   password: String!
# }

type Query {
  getUser: User
}

# type Mutation {
#   createUser(input: UserInput): User
# }
